const { fixture, server, chromium, expect, assert }=require('./p0.browser.cjs');
const path=require('node:path');
function setup(s){
 s.settings.onboarded=true;s.settings.model_ready=true;s.settings.model_labels={'test:one':'Test One'};
 s.personas.forEach(p=>Object.assign(p,{builtin:true,surfaced:true,tools:[],recommends:[],default_connections:[]}));s.personas[0].default=true;
 s.providers=[{name:'test',title:'Test Provider',needs_key:true,configured:true,values:{method:'key'},fields:[{key:'method',label:'连接方式',default:'key',choices:[{value:'key',label:'Key'},{value:'profile',label:'Profile'}]},{key:'api_key',label:'API 密钥',secret:true,required:true,show_when:{method:'key'}},{key:'profile',label:'Profile',default:'main',show_when:{method:'profile'}}],recommended_model:'one',suggested_models:['two']},{name:'openai-codex',title:'Account Provider',auth:'oauth',signed_in:false,fields:[]}];
 s.memories=[{id:7,content:'旧记忆',scope:'global'},{id:8,content:'新增记忆',previous:'',scope:'global'}];s.cloud=false;s.auth=false;
 s.extraRoute=(url,body,req)=>{const p=url.pathname,m=req.method();
  if(p==='/v1/providers/verify')return s.rejectVerify?{ok:false,error:'凭据验证失败'}:{ok:true};
  if(p==='/v1/providers'){if(m==='POST'){if(s.rejectSave)return {ok:false,error:'配置写入失败'};s.providers[0].configured=true;s.providers[0].values={...body.fields};delete s.providers[0].values.api_key;s.settings.model_ready=true;return {ok:true,recommended_model:'one'};}return s.providers;}
  if(p.endsWith('/openai-codex/signin')){s.auth=true;s.providers[1].signed_in=true;return {ok:true};}
  if(p.endsWith('/openai-codex/status'))return {signed_in:s.auth};
  if(p.endsWith('/openai-codex/signout')){s.auth=false;s.providers[1].signed_in=false;return {ok:true};}
  if(p==='/v1/settings/models/add'){if(!s.settings.models.includes(body.model))s.settings.models.push(body.model);return {ok:true};}
  if(p==='/v1/settings/onboarded'){if(s.rejectOnboard)return {ok:false,error:'引导保存失败'};s.settings.onboarded=body.value;return {ok:true};}
  if(p==='/v1/settings/auto-approve-shadow'){if(s.rejectShadow)return {ok:false,error:'影子评估保存失败'};Object.assign(s.settings,body);return {ok:true};}
  if(p==='/v1/personas/install'){if(s.rejectInstall)return {ok:false,error:'安装失败'};const agent={id:'writer',name:'Writer',builtin:false,enabled:false,surfaced:false,description:'# Writer details',tools:['read_file'],recommended_models:['test:one'],recommends:[{kind:'connector',ref:'slack',connected:true}],default_connections:[{connector:'slack',enabled:false,connected:true}]};s.personas=s.personas.filter(x=>x.id!=='writer').concat(agent);return {ok:true,consent:[{...agent,risk:['writes'],connectors:['slack'],mcp:[],messaging:false,recommended_mode:'interactive',source:'test'}]};}
  if(p==='/v1/workspaces/pick')return {ok:true,path:'D:/chosen'};
  if(p.startsWith('/v1/personas/')){const id=decodeURIComponent(p.split('/')[3]),row=s.personas.find(x=>x.id===id);if(p.endsWith('/export'))return {ok:true,path:'D:/chosen/writer.zip'};if(p.endsWith('/connections')){row.default_connections[0].enabled=body.enabled;return {ok:true};}if(m==='DELETE'){if(s.rejectDelete)return {ok:false,error:'删除失败'};s.personas=s.personas.filter(x=>x.id!==id);return {ok:true};}if(m==='POST'){if(body.default)s.personas.forEach(x=>x.default=false);Object.assign(row,body);if(body.enabled)row.surfaced=true;return {ok:true};}return row;}
  if(p==='/v1/cloud/status')return {signed_in:s.cloud};if(p==='/v1/cloud/login'){s.cloud=true;return {ok:true};}
  if(p==='/v1/cloud/gallery')return {ok:true,personas:[{slug:'writer',name:'Writer',publisher:'OpenWorker',tagline:'Draft documents'}]};
  if(p==='/v1/cloud/gallery/writer')return {ok:true,card:{slug:'writer',name:'Writer',pitch_markdown:'# Gallery writer'},capabilities:{tools:['read_file'],risk:['writes']}};
  if(p==='/v1/memory')return {memory:s.memories};
  if(/^\/v1\/memory\/\d+$/.test(p)){if(s.rejectMemory)return {ok:false,error:'撤销失败'};const id=Number(p.split('/').at(-1));if(m==='DELETE')s.memories=s.memories.filter(x=>x.id!==id);else s.memories.find(x=>x.id===id).content=body.content;return {ok:true};}
  if(p==='/v1/audit')return s.rejectAudit?{ok:false,error:'审计不可用'}:{events:[{id:1,tool:'run_shell',approval:'reviewer_denied',stage:'approval',status:'denied',reason:'风险过高',session_id:'s1'}]};
 };
}
const settings=async(page,tab)=>{await page.locator('.surface-nav').getByRole('button',{name:'设置'}).click();if(tab)await page.locator('.subnav').getByRole('button',{name:tab,exact:true}).click();};
const req=(s,p)=>s.requests.filter(r=>r.path===p&&r.method!=='GET').at(-1);
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:process.env.P0_BROWSER_CHANNEL||'msedge',headless:true});const base='http://127.0.0.1:'+server.address().port;let count=0;
 async function check(name,fn,configure=()=>{}){const f=await fixture(browser,base,s=>{setup(s);configure(s);});try{await fn(f);await f.close();console.log('PASS '+(++count)+': '+name);}catch(e){await f.page.screenshot({path:path.join(__dirname,'../dist/p3-failure.png'),fullPage:true});throw e;}}
 try{
 await check('Git install failure retains input; consent, connection defaults, export and deletion',async({page,state})=>{
  await settings(page,'智能体');state.rejectInstall=true;await page.getByLabel('Git 地址',{exact:true}).fill('https://example.test/writer.git');await page.getByRole('button',{name:'从 Git 安装',exact:true}).click();await expect(page.getByRole('alert')).toContainText('安装失败');await expect(page.getByLabel('Git 地址',{exact:true})).toHaveValue('https://example.test/writer.git');state.rejectInstall=false;await page.getByRole('button',{name:'从 Git 安装',exact:true}).click();await expect(page.locator('.persona-consent')).toContainText('read_file');assert.equal(state.personas.at(-1).enabled,false);
  await page.getByRole('button',{name:'确认能力并启用'}).click();await expect.poll(()=>state.personas.at(-1).enabled).toBe(true);await page.locator('.list-card').filter({hasText:'Writer'}).getByRole('button',{name:'查看详情'}).click();await page.getByLabel('新会话默认启用').check();await expect.poll(()=>req(state,'/v1/personas/writer/connections')?.body).toEqual({connector:'slack',enabled:true});await page.getByRole('button',{name:'导出 ZIP'}).click();await expect(page.getByRole('status')).toContainText('writer.zip');state.rejectDelete=true;await page.getByRole('button',{name:'删除智能体'}).click();await expect(page.getByRole('alert')).toContainText('删除失败');state.rejectDelete=false;await page.getByRole('button',{name:'删除智能体'}).click();await expect.poll(()=>state.personas.some(p=>p.id==='writer')).toBe(false);
 });
 await check('folder, ZIP and signed-in gallery imports preserve source protocol',async({page,state})=>{
  await settings(page,'智能体');await page.getByRole('button',{name:'从目录安装'}).click();await expect.poll(()=>req(state,'/v1/personas/install')?.body.dir).toBe('D:/chosen');await page.getByRole('button',{name:'暂不启用'}).click();await page.getByLabel('智能体 ZIP').setInputFiles({name:'bundle.zip',mimeType:'application/zip',buffer:Buffer.from('zip fixture')});await expect.poll(()=>req(state,'/v1/personas/install')?.body.zip_b64).toBe(Buffer.from('zip fixture').toString('base64'));await page.getByRole('button',{name:'暂不启用'}).click();await page.getByRole('button',{name:'浏览图库'}).click();await page.getByRole('button',{name:'登录云账号',exact:true}).click();await page.getByRole('button',{name:'刷新图库'}).click();await page.getByRole('button',{name:'查看详情'}).click();await expect(page.locator('.capabilities')).toContainText('read_file');await page.getByRole('button',{name:'安装此智能体'}).click();await expect.poll(()=>req(state,'/v1/personas/install')?.body.gallery_slug).toBe('writer');
 });
 await check('default persona and visibility persist into new chats',async({page,state})=>{
  await settings(page,'智能体');await page.locator('.list-card').filter({hasText:'Chat'}).getByRole('button',{name:'查看详情'}).click();await page.getByLabel('在选择器中显示').uncheck();await expect.poll(()=>state.personas[1].surfaced).toBe(false);await page.getByLabel('在选择器中显示').check();await page.getByRole('button',{name:'设为默认智能体'}).click();await expect.poll(()=>state.personas[1].default).toBe(true);await page.locator('.new-button').click();await expect(page.getByRole('button',{name:'选择智能体'})).toContainText('Chat');
 });
 await check('provider verify/save failures, conditional fields, recommendations and OAuth',async({page,state})=>{
  await settings(page,'模型');const card=page.locator('.provider-card').filter({hasText:'Test Provider'});await card.getByLabel('API 密钥').fill('secret');state.rejectVerify=true;await card.getByRole('button',{name:'测试并保存'}).click();await expect(page.getByRole('alert')).toContainText('凭据验证失败');assert.equal(req(state,'/v1/providers'),undefined);state.rejectVerify=false;state.rejectSave=true;await card.getByRole('button',{name:'测试并保存'}).click();await expect(page.getByRole('alert')).toContainText('配置写入失败');await expect(card.getByLabel('API 密钥')).toHaveValue('secret');state.rejectSave=false;await card.getByRole('button',{name:'测试并保存'}).click();await expect(page.getByRole('status')).toContainText('连接测试通过');await expect(card.getByLabel('API 密钥')).toHaveValue('');await card.getByLabel('连接方式').selectOption('profile');await expect(card.getByLabel('API 密钥')).toHaveCount(0);await card.getByRole('button',{name:'测试并保存'}).click();await expect.poll(()=>req(state,'/v1/providers')?.body.fields).toEqual({method:'profile',profile:'main'});await card.getByRole('button',{name:'two',exact:true}).click();await expect.poll(()=>req(state,'/v1/settings/models/add')?.body.model).toBe('test:two');await page.getByRole('button',{name:'登录账号',exact:true}).click();await expect(page.getByRole('button',{name:'退出账号',exact:true})).toBeVisible();await page.getByRole('button',{name:'退出账号',exact:true}).click();await expect.poll(()=>state.auth).toBe(false);
 });
 await check('first-run setup saves completion only on success and allows skipping connectors',async({page,state})=>{
  const dialog=page.getByRole('dialog',{name:'首次使用引导'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'下一步',exact:true})).toBeDisabled();await dialog.getByLabel('API 密钥').fill('new-key');await dialog.getByRole('button',{name:'测试并保存'}).click();await dialog.getByRole('button',{name:'下一步',exact:true}).click();state.rejectOnboard=true;await dialog.getByRole('button',{name:'跳过连接器并开始'}).click();await expect(dialog.getByRole('alert')).toContainText('引导保存失败');assert.equal(state.settings.onboarded,false);state.rejectOnboard=false;await dialog.getByRole('button',{name:'跳过连接器并开始'}).click();await expect(dialog).toHaveCount(0);await page.reload();await expect(dialog).toHaveCount(0);await page.locator('.composer textarea').fill('我的首次任务');await page.locator('.send-button').click();await expect.poll(()=>state.sent.some(m=>m.type==='user_message'&&m.text==='我的首次任务')).toBe(true);
 },s=>{s.settings.onboarded=false;s.settings.model_ready=false;s.providers[0].configured=false;});
 await check('memory additions and edits undo correctly; failed undo remains retryable; memory view refreshes',async({page,state})=>{
  state.emit('s1','memory_saved',{id:8,content:'新增记忆'});await expect(page.locator('.memory-notice')).toContainText('已新增记忆');state.rejectMemory=true;await page.getByRole('button',{name:'撤销记忆'}).click();await expect(page.getByRole('alert')).toContainText('撤销失败');state.rejectMemory=false;await page.getByRole('button',{name:'撤销记忆'}).click();await expect(page.locator('.memory-notice')).toContainText('已撤销记忆');assert.ok(!state.memories.some(m=>m.id===8));state.memories[0].content='修改后';state.emit('s1','memory_saved',{id:7,summary:'更新信息',previous:'旧记忆'});await page.getByRole('button',{name:'撤销记忆'}).click();await expect.poll(()=>state.memories[0].content).toBe('旧记忆');await settings(page,'记忆');await expect(page.locator('.memory-row textarea')).toHaveValue('旧记忆');state.memories[0].content='再次修改';state.emit('s1','memory_saved',{id:7,content:'再次修改',previous:'旧记忆'});await expect(page.locator('.memory-row textarea')).toHaveValue('再次修改');
 });
 await check('audit approval data, system theme, locale persistence and shadow evaluation',async({page,state})=>{
  await page.locator('.surface-nav').getByRole('button',{name:'活动审计'}).click();await expect(page.locator('.audit-row')).toContainText('reviewer_denied');await expect(page.locator('.audit-row')).toContainText('approval');state.rejectAudit=true;await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.getByRole('alert')).toContainText('审计不可用');await expect(page.locator('.audit-row')).toContainText('reviewer_denied');state.rejectAudit=false;await settings(page,'通用');await page.getByLabel('外观',{exact:true}).selectOption('auto');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.emulateMedia({colorScheme:'light'});await expect(page.locator('html')).toHaveAttribute('data-theme','light');state.rejectShadow=true;await page.getByLabel('自动审批影子评估').check();await expect(page.getByRole('alert')).toContainText('影子评估保存失败');state.rejectShadow=false;await page.getByLabel('自动审批影子评估').check();await expect.poll(()=>state.settings.auto_approve_shadow).toBe(true);
  await page.getByLabel('语言',{exact:true}).selectOption('en');await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('.subnav').getByRole('button',{name:'General',exact:true})).toBeVisible();await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','en');await page.locator('.surface-nav').getByRole('button',{name:'Settings'}).click();await page.getByLabel('Language',{exact:true}).selectOption('auto');await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await page.getByLabel('语言',{exact:true}).selectOption('auto');await page.evaluate(()=>{Object.defineProperty(navigator,'language',{value:'en-US',configurable:true});window.dispatchEvent(new Event('languagechange'));});await expect(page.locator('html')).toHaveAttribute('lang','en');await page.getByLabel('Language',{exact:true}).selectOption('zh');await page.locator('.brand .pin').click();await page.setViewportSize({width:430,height:900});await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:path.join(__dirname,'../dist/p3-narrow.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 });
 await check('keyless onboarding requires a real verification and keeps readiness when navigating back',async({page,state})=>{
  const dialog=page.getByRole('dialog',{name:'首次使用引导'});await expect(dialog.getByRole('button',{name:'下一步',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'测试并保存'}).click();await dialog.getByRole('button',{name:'下一步',exact:true}).click();await dialog.getByRole('button',{name:'上一步',exact:true}).click();await expect(dialog.getByRole('button',{name:'下一步',exact:true})).toBeEnabled();await page.setViewportSize({width:430,height:900});await page.screenshot({path:path.join(__dirname,'../dist/p3-onboarding.png'),fullPage:true});assert.equal(await dialog.evaluate(el=>el.scrollWidth>el.clientWidth+1),false);
 },s=>{s.settings.onboarded=false;s.providers[0].needs_key=false;s.providers[0].fields=[];});
 await check('authenticated persona screenshots and English switching preserve user content',async({page,state})=>{
  let mediaAuth='';await page.route('**/v1/personas/chat/media/one.png',route=>{mediaAuth=route.request().headers()['x-openworker-token'];return route.fulfill({status:200,contentType:'image/png',headers:{'Access-Control-Allow-Origin':'*'},body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN1sAAAAASUVORK5CYII=','base64')});});
  await settings(page,'智能体');await page.locator('.list-card').filter({hasText:'Chat'}).getByRole('button',{name:'查看详情'}).click();await expect(page.locator('.persona-media img')).toHaveCount(1);await expect.poll(()=>mediaAuth).toBe('test-token');await page.screenshot({path:path.join(__dirname,'../dist/p3-persona.png'),fullPage:true});await page.locator('.subnav').getByRole('button',{name:'通用',exact:true}).click();await page.getByLabel('语言',{exact:true}).selectOption('en');await page.locator('.session-row').first().click();await expect(page.locator('.title-block strong')).toHaveText('设置');state.emit('s1','memory_saved',{id:7,content:'设置',previous:'原文'});await expect(page.locator('.memory-notice p')).toHaveText('设置');await expect(page.locator('.memory-notice strong')).toHaveText('Memory updated');
 },s=>{s.personas[1].media=['one.png'];s.sessions[0].title='设置';});
 console.log(count+' P3 browser scenarios passed.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
