<script setup>
import { t } from '../i18n';
import { computed, ref, watch } from 'vue';
import { checked } from '../api-result.js';
import { accountAction, allowUser, disallowUser, slackDirectory, slackOwner, connectorAction, resolveUnauthorized, getConnectorStatus } from '../connectors-api.js';
import { lines } from '../config-input.js';
const props=defineProps({connector:Object});const emit=defineEmits(['change']);
const busy=ref(false),error=ref(''),people=ref({}),queries=ref({}),senders=ref(''),labels=ref(''),hidden=ref(''),health=ref(null);
const groups=computed(()=>{
 const c=props.connector;
 if(c.name==='slack')return c.mode==='relay'?(c.workspaces || []).map(w=>({...w,id:w.team_id,label:w.account || w.team_id,collection:'workspaces'})):[{...c,id:'default',label:c.account || '默认工作区',collection:'workspaces'}];
 if(c.name==='github')return (c.installations || []).map(w=>({...w,id:w.installation_id,label:w.account_login,collection:'installations'}));
 if(c.name==='hubspot')return (c.portals || []).map(w=>({...w,id:w.hub_id,label:w.name || w.hub_id,collection:'portals'}));
 if(c.two_way && !c.accounts?.length)return [{...c,id:'default',label:c.account || c.title,collection:'accounts'}];
 return (c.accounts || []).map(w=>({...w,id:w.email || w.account_id,label:w.email || w.name || w.account_id,collection:'accounts'}));
});
async function act(fn){if(busy.value)return;busy.value=true;error.value='';try{checked(await fn());emit('change');}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function search(group){try{people.value[group.id]=checked(await slackDirectory(group.id,queries.value[group.id] || '')).members || [];}catch(e){error.value=e.message;}}
function team(group){return group.id==='default'?undefined:group.id;}
watch(()=>props.connector,async c=>{if(['slack','github'].includes(c.name)){try{const result=await getConnectorStatus(c.name);if(props.connector.name===c.name)health.value=result;}catch(e){error.value=e.message;}}});
watch(()=>props.connector.name,async()=>{const c=props.connector;senders.value=(c.filters?.senders || []).join('\n');labels.value=(c.filters?.labels || []).join('\n');hidden.value=(c.hidden_fields || []).join('\n');people.value={};queries.value={};error.value='';health.value=null;if(['slack','github'].includes(c.name)){try{health.value=await getConnectorStatus(c.name);}catch(e){error.value=e.message;}}},{immediate:true});
</script>
<template><section class="connector-accounts"><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p><p v-if="health?.relay" class="status-note">{{ t("连接状态：") }}{{ health.relay.state }}{{ t(" · 重连 ") }}{{ health.relay.reconnects }}{{ t(" 次 ") }}{{ health.relay.last_error }}</p><fieldset :disabled="busy">
<article v-for="group in groups" :key="group.id" class="card account-group"><h3>{{ group.label }} <small v-if="group.default">{{ t("默认账号") }}</small></h3><p v-if="group.needs_reauth" class="error-text">{{ t("此账号需要重新授权，请使用上方授权入口。") }}</p><p v-if="group.repo_selection">{{ t("仓库访问：") }}{{ group.repo_selection }} · {{ group.account_type }}</p><p v-if="group.access">{{ t("访问权限：") }}{{ group.access }}{{ group.sandbox?t(" · 沙箱"):'' }}</p><p v-if="health?.teams?.[group.id]?.token_ok===false || health?.installs?.[group.id]?.token_ok===false" class="error-text">{{ t("令牌不可用，请重新连接。") }}</p><div class="actions"><button v-if="['accounts','portals'].includes(group.collection)&&!group.default" class="btn" @click="act(()=>accountAction(connector.name,group.collection,group.id,'default'))">{{ t("设为默认") }}</button><button v-if="group.id!=='default'" class="btn danger" @click="act(()=>accountAction(connector.name,group.collection,group.id,'disconnect'))">{{ t("断开此账号") }}</button></div>
<template v-if="connector.two_way || connector.name==='slack' || connector.name==='github'"><h4>{{ t("可发起任务的人员") }}</h4><p v-if="group.allow_all">{{ t("允许所有人员 ") }}<button class="btn" @click="act(()=>disallowUser(connector.name,'*',team(group)))">{{ t("改为仅允许名单人员") }}</button></p><div v-for="user in group.allowed_users || []" :key="user" class="permission-person"><span>{{ group.allowed_user_names?.[user] || user }}</span><button class="btn" @click="act(()=>disallowUser(connector.name,user,team(group)))">{{ t("移除") }}</button></div><form class="actions" @submit.prevent="act(()=>allowUser(connector.name,queries[group.id],team(group)))"><input v-model="queries[group.id]" :aria-label="(t(&quot;人员 &quot;) + (group.label))" :placeholder="t(&quot;用户 ID / GitHub 登录名&quot;)" required /><button class="btn">{{ t("允许此人员") }}</button><button v-if="connector.name==='slack'" type="button" class="btn" @click="search(group)">{{ t("搜索人员") }}</button></form><button v-for="person in people[group.id] || []" :key="person.id" class="btn" @click="act(()=>allowUser(connector.name,person.id,team(group),person.name))">{{ t("添加 ") }}{{ person.name }}（{{ person.handle }}）</button></template>
<template v-if="connector.name==='slack'"><h4>{{ t("审批负责人") }}</h4><p v-if="!(group.approval_owner_ids || []).length" class="muted">{{ t("尚未指定审批负责人") }}</p><div v-for="owner in group.approval_owner_ids || []" :key="owner" class="permission-person"><span>{{ group.approval_owner_names?.[owner] || owner }}</span><button v-if="group.id==='default'" class="btn" @click="act(()=>slackOwner(owner,'remove'))">{{ t("移除审批负责人") }}</button></div><template v-if="group.id==='default'"><button class="btn" :disabled="!queries[group.id]" @click="act(()=>slackOwner(queries[group.id],'add'))">{{ t("将输入人员设为审批负责人") }}</button></template><p v-else class="muted">{{ t("托管工作区的审批负责人由安装者设置。") }}</p></template>
</article>
<form v-if="connector.name==='gmail'" class="card form-card" @submit.prevent="act(()=>connectorAction('gmail','filters',{senders:lines(senders),labels:lines(labels)},'PATCH'))"><h3>{{ t("不向智能体展示的邮件") }}</h3><label>{{ t("发件人（每行一个）") }}<textarea v-model="senders" rows="3"></textarea></label><label>{{ t("邮件标签（每行一个）") }}<textarea v-model="labels" rows="3"></textarea></label><button class="btn">{{ t("保存邮件过滤") }}</button></form>
<form v-if="connector.name==='hubspot'" class="card form-card" @submit.prevent="act(()=>connectorAction('hubspot','hidden-fields',{hidden_fields:lines(hidden)},'PATCH'))"><label>{{ t("隐藏的 CRM 字段（每行一个）") }}<textarea v-model="hidden" rows="4"></textarea></label><button class="btn">{{ t("保存隐藏字段") }}</button></form>
<section v-if="connector.unauthorized?.length"><h3>{{ t("未授权人员的消息") }}</h3><article v-for="item in connector.unauthorized" :key="item.id" class="card"><strong>{{ item.user_name || item.user_id }} · {{ item.chat_name || item.chat_id }}</strong><p>{{ item.text }}</p><div class="actions"><button class="btn" @click="act(()=>resolveUnauthorized(connector.name,item.id,'dismiss'))">{{ t("忽略") }}</button><button class="btn" @click="act(()=>resolveUnauthorized(connector.name,item.id,'allow'))">{{ t("允许此人") }}</button><button class="btn primary" @click="act(()=>resolveUnauthorized(connector.name,item.id,'allow_deliver'))">{{ t("允许并投递此消息") }}</button></div></article></section>
</fieldset></section></template>
