<script setup>
import { t } from '../i18n';
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import { getSessions, getConnectors } from '../api';
import { checked } from '../api-result.js';
import { getSubscriptions, getInboxRouting, getDmRoute, getUnrouted, setDmRoute, setInboxBinding, subscribeChannel, unsubscribeChannel } from '../inbox-api.js';
import { splitAddress } from '../config-input.js';
import ChannelPicker from './ChannelPicker.vue';
const emit=defineEmits(['open-connectors']);const sessions=ref([]),connectors=ref([]),subscriptions=ref([]),bindings=ref([]),unrouted=ref([]),dm=ref(''),target=ref(''),channel=ref(''),session=ref(''),error=ref(''),busy=ref(false);let timer,disposed=false;
const missingOwner=computed(()=>{const [platform,address]=splitAddress(target.value);if(platform!=='slack'||!address)return false;const slack=connectors.value.find(c=>c.name==='slack');const owners=address.includes('/')?slack?.workspaces?.find(w=>w.team_id===address.split('/')[0])?.approval_owner_ids:slack?.approval_owner_ids;return !owners?.length;});
async function load(){try{[sessions.value,connectors.value,subscriptions.value,bindings.value,dm.value,unrouted.value]=await Promise.all([getSessions(),getConnectors(),getSubscriptions(),getInboxRouting(),getDmRoute(),getUnrouted()]);}catch(e){error.value=e.message;}}
async function poll(){if(!busy.value)await load();if(!disposed)timer=setTimeout(poll,5000);}
async function act(fn){busy.value=true;error.value='';try{checked(await fn());await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
onMounted(poll);onBeforeUnmount(()=>{disposed=true;clearTimeout(timer);});
</script>
<template><section class="inbox-routing"><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p><fieldset :disabled="busy"><div class="workflow-grid"><section class="card form-card"><h3>{{ t("后台审批投递") }}</h3><p>{{ t("当前：") }}{{ bindings.find(b=>b.name==='default')?.channel ? `${bindings.find(b=>b.name==='default').channel}:${bindings.find(b=>b.name==='default').target}` : t("仅应用内收件箱") }}</p><ChannelPicker v-model="target" :label="t(&quot;审批投递频道&quot;)" /><p v-if="missingOwner" class="error-text">{{ t("请先为该 Slack 工作区配置审批负责人。") }}<button class="btn" @click="emit('open-connectors','slack')">{{ t("配置 Slack") }}</button></p><div class="actions"><button class="btn" :disabled="!target.trim()||missingOwner" @click="act(()=>setInboxBinding('default',...splitAddress(target)))">{{ t("保存投递频道") }}</button><button class="btn" @click="act(()=>setInboxBinding('default',null,''))">{{ t("仅应用内") }}</button></div></section><section class="card form-card"><h3>{{ t("私信路由") }}</h3><label>{{ t("接收私信的会话") }}<select :value="dm" @change="act(()=>setDmRoute($event.target.value))"><option value="">{{ t("未指定") }}</option><option v-for="row in sessions.filter(s=>!s.session_id.startsWith('__'))" :key="row.session_id" :value="row.session_id">{{ row.title || row.session_id }}</option></select></label></section></div>
<section class="card form-card"><h3>{{ t("频道订阅") }}</h3><label>{{ t("目标会话") }}<select v-model="session"><option value="">{{ t("请选择") }}</option><option v-for="row in sessions.filter(s=>!s.session_id.startsWith('__'))" :key="row.session_id" :value="row.session_id">{{ row.title || row.session_id }}</option></select></label><ChannelPicker v-model="channel" /><button class="btn" :disabled="!session||!channel.trim()" @click="act(()=>subscribeChannel(session,channel))">{{ t("订阅频道") }}</button><div v-for="row in subscriptions" :key="`${row.session_id}:${row.channel}`" class="subscription-row"><span>{{ row.channel_name || row.channel }} → {{ row.session_title || row.session_id }}<small v-if="row.collision" class="error-text">{{ t("此频道同时接收审批投递，请检查路由") }}</small></span><button class="btn" @click="act(()=>unsubscribeChannel(row.session_id,row.channel))">{{ t("取消订阅") }}</button></div></section></fieldset>
<section class="card"><h3>{{ t("未路由消息") }}</h3><p class="muted">{{ t("配置私信或频道路由以处理后续消息；未授权人员的待处理消息请到对应连接器处理。") }}</p><p v-if="!unrouted.length">{{ t("暂无未路由消息") }}</p><article v-for="(row,i) in unrouted" :key="i" class="unrouted-row"><strong>{{ row.source }} · {{ row.sender }}</strong><small>{{ new Date(row.ts*1000).toLocaleString() }} · {{ row.reason }}</small><p>{{ row.text }}</p><button class="btn" @click="emit('open-connectors',row.source?.split(':')[0])">{{ t("查看来源连接器") }}</button></article></section></section></template>
