<script setup>
import { computed, ref } from 'vue';
import QuestionPrompt from './QuestionPrompt.vue';
import ApprovalPrompt from './ApprovalPrompt.vue';
import MarkdownView from './MarkdownView.vue';
import { checked, resolveInboxItem } from '../p2api';
import { parkedPrompt, parkedResolution } from '../p2';
const props=defineProps({item:Object,inline:Boolean,liveItem:Object,autoApprove:Boolean});const emit=defineEmits(['resolved','open-session']);
const busy=ref(false),error=ref(''),resolved=ref(false);const prompt=computed(()=>parkedPrompt(props.item,props.liveItem));
async function resolve(value){if(busy.value||resolved.value)return;busy.value=true;error.value='';try{checked(await resolveInboxItem(props.item.id,value));resolved.value=true;emit('resolved',{...props.item,resolution:value});}catch(e){error.value=e.message;emit('resolved',null);}finally{busy.value=false;}}
</script>
<template><article class="card inbox-card"><header><strong>{{ item.title }}</strong><small>{{ item.kind }} · {{ item.session_title || item.session_id }} · {{ item.created_at }}</small><button v-if="!inline && item.session_exists!==false" class="btn" @click="emit('open-session',{session_id:item.session_id,workspace:item.session_workspace,agent:item.session_agent})">打开所属会话</button></header><p v-if="error" class="error-text" role="alert">{{ error }}</p><template v-if="item.state==='resolved'||resolved"><MarkdownView :text="item.body" /><p class="muted">已处理：{{ item.resolution || '已提交' }}</p></template><fieldset v-else :disabled="busy"><QuestionPrompt v-if="item.kind==='question'" :item="prompt" @answer="resolve(String($event))" /><ApprovalPrompt v-else-if="['directory','plan','tool'].includes(item.kind) || (inline && item.kind==='approval' && (item.data?.tool || liveItem?.name))" :item="prompt" :run-task="!!item.data?.task_id" :auto-approve="autoApprove" @resolve="resolve(parkedResolution(item,$event,prompt.kind))" /><template v-else><MarkdownView :text="item.body" /><details v-if="item.data?.arguments"><summary>操作详情</summary><pre>{{ JSON.stringify(item.data.arguments,null,2) }}</pre></details><div class="actions"><template v-if="item.kind==='approval'"><button class="btn primary" @click="resolve('allow')">允许一次</button><button v-if="item.data?.task_id && item.data?.standing_target" class="btn" @click="resolve('always_task')">此自动化每次允许 {{ item.data.standing_target }}</button><button class="btn" @click="resolve('deny')">拒绝</button></template><button v-else class="btn" @click="resolve('seen')">标为已读</button></div></template></fieldset></article></template>
