<script setup>
import { t } from '../i18n';
import { ref, onMounted, onBeforeUnmount, computed } from 'vue';
import { addMcpServer, getMcpServers, updateMcpServer, deleteMcpServer } from '../api';
import { checked, getMcpTools, getMcpTrust, revokeMcpTrust, convertMcpTrust, connectMcp, signoutMcp, reloadMcp, revealMcpConfig } from '../p2api';
import { mcpConfig } from '../settings';
import { objectJson, mcpImports } from '../p2';
const servers=ref([]),show=ref(false),error=ref(''),busy=ref(false),selection=ref(''),tools=ref([]),trust=ref(null),included=ref([]),importText=ref(''),importMode=ref(false);
const empty=()=>({name:'',transport:'stdio',command:'',args:'',url:'',env:'{}',headers:'{}',cwd:'',auth:''});const form=ref(empty());
const server=computed(()=>servers.value.find(s=>s.name===selection.value));let timer,disposed=false,loadId=0;
async function refresh(){try{servers.value=await getMcpServers();}catch(e){error.value=e.message;}}
async function poll(){await refresh();if(!disposed)timer=setTimeout(poll,4000);}
async function act(fn){if(busy.value)return;busy.value=true;error.value='';try{checked(await fn());await refresh();}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function add(){await act(async()=>{if(importMode.value){const entries=mcpImports(importText.value);for(const [name,config]of entries)checked(await addMcpServer(name,config));}else{const config={...mcpConfig(form.value),...(form.value.cwd?{cwd:form.value.cwd}:{})};if(form.value.transport==='stdio')config.env=objectJson(form.value.env,'环境变量');else {config.headers=objectJson(form.value.headers,'HTTP 请求头');if(form.value.auth)config.auth=form.value.auth;}checked(await addMcpServer(form.value.name.trim(),config));}show.value=false;form.value=empty();importText.value='';return {ok:true};});}
async function inspect(name,withTools=true){selection.value=name;if(withTools)tools.value=[];trust.value=null;error.value='';const id=++loadId;try{const t=checked(await getMcpTrust(name));if(id!==loadId)return;trust.value=t;if(withTools){const result=checked(await getMcpTools(name));if(id!==loadId)return;tools.value=result.tools || [];included.value=server.value?.config?.include_tools || tools.value.filter(t=>!(server.value?.config?.exclude_tools || []).includes(t.name)).map(t=>t.name);}}catch(e){if(id===loadId)error.value=e.message;}}
function saveTools(){act(async()=>{checked(await updateMcpServer(selection.value,{include_tools:included.value,exclude_tools:tools.value.filter(t=>!included.value.includes(t.name)).map(t=>t.name)}));return {ok:true};});}
async function trustAction(fn){await act(fn);if(!error.value)await inspect(selection.value,false);}
onMounted(poll);onBeforeUnmount(()=>{disposed=true;loadId++;clearTimeout(timer);});
</script>
<template><section class="mcp-manager"><div class="page-head"><h2>{{ t("自定义 MCP 服务器") }}</h2><div class="actions"><button class="btn" @click="show=!show">{{ t("＋ 自定义 MCP") }}</button><button class="btn" :disabled="busy" @click="act(reloadMcp)">{{ t("重新加载") }}</button><button class="btn" :disabled="busy" @click="act(revealMcpConfig)">{{ t("打开配置文件") }}</button></div></div><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p>
<form v-if="show" class="card form-card" @submit.prevent="add"><fieldset :disabled="busy" class="form-card"><label><input v-model="importMode" type="checkbox" />{{ t("导入 JSON 配置") }}</label><label v-if="importMode">MCP JSON<textarea v-model="importText" rows="8" placeholder='{"mcpServers":{"example":{"command":"npx","args":[]}}}' required></textarea></label><template v-else><label>{{ t("服务器名称") }}<input v-model="form.name" required /></label><label>{{ t("传输方式") }}<select v-model="form.transport"><option value="stdio">{{ t("本地命令（stdio）") }}</option><option value="http">HTTP</option></select></label><template v-if="form.transport==='stdio'"><label>{{ t("可执行程序") }}<input v-model="form.command" required /></label><label>{{ t("启动参数（每行一个）") }}<textarea v-model="form.args" rows="3"></textarea></label><label>{{ t("工作目录") }}<input v-model="form.cwd" /></label><label>{{ t("环境变量 JSON") }}<textarea v-model="form.env" rows="3"></textarea></label></template><template v-else><label>{{ t("服务器 URL") }}<input v-model="form.url" required /></label><label>{{ t("HTTP 请求头 JSON") }}<textarea v-model="form.headers" rows="3"></textarea></label><label>{{ t("认证方式") }}<select v-model="form.auth"><option value="">{{ t("无 OAuth / 使用请求头") }}</option><option value="oauth">OAuth</option></select></label></template></template><div class="actions"><button class="btn primary">{{ t("添加服务器") }}</button><button type="button" class="btn" @click="show=false">{{ t("取消") }}</button></div></fieldset></form>
<article v-for="row in servers" :key="row.name" class="card mcp-server"><h3>{{ row.name }}</h3><p>{{ row.transport }} · {{ row.status }} · {{ row.tool_count ?? 0 }}{{ t(" 个工具") }}</p><p v-if="row.last_error" class="error-text">{{ row.last_error }}</p><small v-if="row.last_test_at">{{ t("最近测试：") }}{{ new Date(row.last_test_at*1000).toLocaleString() }}</small><div class="actions"><label><input type="checkbox" :checked="row.enabled" :disabled="busy" @change="act(()=>updateMcpServer(row.name,{enabled:!row.enabled}))" />{{ t("启用") }}</label><button class="btn" :disabled="busy" @click="act(()=>connectMcp(row.name))">{{ row.auth==='oauth'?t("OAuth 登录 / 测试"):t("测试连接") }}</button><button v-if="row.auth_hint && row.auth!=='oauth'" class="btn" @click="act(async()=>{checked(await updateMcpServer(row.name,{auth:'oauth'}));return connectMcp(row.name);})">{{ t("改用 OAuth 登录") }}</button><button v-if="row.auth==='oauth'" class="btn" :disabled="busy" @click="act(()=>signoutMcp(row.name))">{{ t("退出 OAuth") }}</button><button class="btn" :disabled="busy" @click="inspect(row.name)">{{ t("查看工具与信任") }}</button><button class="btn danger" :disabled="busy" @click="act(()=>deleteMcpServer(row.name))">{{ t("删除服务器") }}</button></div>
<section v-if="selection===row.name" class="mcp-tools"><p v-if="trust?.legacy_dont_ask" class="status-note">{{ t("此服务器仍使用旧的整台服务器信任。") }}<button class="btn" @click="trustAction(()=>convertMcpTrust(row.name))">{{ t("迁移为逐工具信任") }}</button></p><p class="muted">{{ t("持久信任在工具审批时授予，可在此撤销；未信任的工具仍按会话审批模式执行。") }}</p><div v-for="tool in tools" :key="tool.name" class="toggle-row"><label><input v-model="included" type="checkbox" :value="tool.name" />{{ tool.name }}<small>{{ tool.description }}</small></label></div><button v-if="tools.length" class="btn" :disabled="busy" @click="saveTools">{{ t("保存工具选择") }}</button><div v-for="tool in trust?.tools || []" :key="tool" class="permission-person">{{ tool }}{{ t(" · 已信任") }}<button class="btn" :disabled="busy" @click="trustAction(()=>revokeMcpTrust(row.name,tool))">{{ t("撤销信任") }}</button></div></section></article><p v-if="!servers.length" class="empty-card">{{ t("没有自定义 MCP 服务器。") }}</p></section></template>
