<script setup>
import { t } from '../i18n';
import { ref,onMounted,onBeforeUnmount,watch } from 'vue';
import { checked,getSessionConnections,setSessionConnection,getUnattended,setUnattended,getSubscriptions,subscribeChannel,unsubscribeChannel } from '../p2api';
import ChannelPicker from './ChannelPicker.vue';
const props=defineProps({sessionId:String,persona:String});const emit=defineEmits(['change','open-connectors']);
const connections=ref({connected:[],recommended:[]}),unattended=ref(false),subscriptions=ref([]),channel=ref(''),error=ref(''),busy=ref(false);let timer,disposed=false,version=0;
async function load(){const id=++version;try{const [con,mode,subs]=await Promise.all([getSessionConnections(props.sessionId,props.persona),getUnattended(props.sessionId),getSubscriptions()]);if(id!==version)return;connections.value=con;unattended.value=mode;subscriptions.value=subs.filter(s=>s.session_id===props.sessionId);}catch(e){if(id===version)error.value=e.message;}}
async function poll(){if(!busy.value)await load();if(!disposed)timer=setTimeout(poll,4000);}
async function act(fn){busy.value=true;error.value='';try{checked(await fn());await load();emit('change');}catch(e){error.value=e.message;}finally{busy.value=false;}}
watch(()=>props.sessionId,()=>{connections.value={connected:[],recommended:[]};subscriptions.value=[];channel.value='';load();});onMounted(poll);onBeforeUnmount(()=>{disposed=true;version++;clearTimeout(timer);});
</script>
<template><section class="session-integrations"><h3>{{ t("后台处理") }}</h3><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p><fieldset :disabled="busy"><label class="toggle-row"><span>{{ t("无人值守") }}<small>{{ t("审批和问题进入收件箱，仍需由你处理。") }}</small></span><input type="checkbox" :checked="unattended" @change="act(()=>setUnattended(sessionId,!unattended))" /></label><h3>{{ t("本会话连接器") }}</h3><label v-for="row in connections.connected || []" :key="row.connector" class="toggle-row"><span>{{ row.connector }}<small>{{ t("全局已连接 · ") }}{{ row.detail }}</small></span><input type="checkbox" :checked="row.enabled" @change="act(()=>setSessionConnection(sessionId,row.connector,!row.enabled))" /></label><button v-for="row in connections.recommended?.filter(r=>!r.connected) || []" :key="row.connector" class="btn" @click="emit('open-connectors',row.connector)">{{ t("连接 ") }}{{ row.connector }} · {{ row.reason }}</button><h3>{{ t("此会话频道订阅") }}</h3><ChannelPicker v-model="channel" /><button class="btn" :disabled="!channel.trim()" @click="act(()=>subscribeChannel(sessionId,channel))">{{ t("订阅到本会话") }}</button><div v-for="row in subscriptions" :key="row.channel" class="subscription-row"><span>{{ row.channel_name || row.channel }}<small v-if="row.collision" class="error-text">{{ t("与审批投递频道相同") }}</small></span><button class="btn" @click="act(()=>unsubscribeChannel(sessionId,row.channel))">{{ t("取消订阅") }}</button></div></fieldset></section></template>
