<script setup>
import { t } from '../i18n';
import { ref,watch,onMounted,onBeforeUnmount,nextTick } from 'vue';
import { checked,getTeamChat,postTeamChat } from '../p2api';
const props=defineProps({teamId:String});const emit=defineEmits(['close']);
const chat=ref(null),draft=ref(''),error=ref(''),busy=ref(false),scroller=ref(null),bottom=ref(true);let timer,disposed=false,version=0;
async function load(){const id=++version;try{const result=checked(await getTeamChat(props.teamId));if(id!==version)return;chat.value=result;if(bottom.value)nextTick(()=>{if(scroller.value)scroller.value.scrollTop=scroller.value.scrollHeight;});}catch(e){if(id===version)error.value=e.message;}}
async function poll(){await load();if(!disposed)timer=setTimeout(poll,3000);}
async function send(){if(!draft.value.trim()||busy.value)return;busy.value=true;error.value='';try{checked(await postTeamChat(props.teamId,draft.value.trim()));draft.value='';bottom.value=true;await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
watch(()=>props.teamId,()=>{chat.value=null;draft.value='';load();});onMounted(poll);onBeforeUnmount(()=>{disposed=true;version++;clearTimeout(timer);});
</script>
<template><section class="team-chat"><header><button class="btn" @click="emit('close')">{{ t("返回会话") }}</button><h2>{{ t("团队聊天室") }}</h2></header><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p><p v-if="chat && !chat.enabled" class="status-note">{{ t("此团队未启用聊天。") }}</p><p class="muted">{{ chat?.members?.map(m=>m.name).join(' · ') }}</p><div ref="scroller" class="team-chat-scroll" @scroll="bottom=$event.target.scrollHeight-$event.target.scrollTop-$event.target.clientHeight<60"><article v-for="message in chat?.messages || []" :key="message.seq"><header><strong>{{ message.author_role==='user'?t("你"):message.author }}</strong><small>{{ message.author_role }} · {{ message.ts }}</small></header><p><template v-for="(part,i) in message.text.split(/(@[\w.-]+)/g)" :key="i"><mark v-if="part.startsWith('@') && chat.members?.some(m=>m.name===part.slice(1))">{{ part }}</mark><template v-else>{{ part }}</template></template></p></article></div><form class="team-chat-compose" @submit.prevent="send"><input v-model="draft" :aria-label="t(&quot;团队聊天消息&quot;)" :placeholder="t(&quot;向团队发送消息，支持 @成员&quot;)" :disabled="!chat?.enabled" /><button class="btn primary" :disabled="busy||!chat?.enabled||!draft.trim()">{{ t("发送到团队") }}</button></form></section></template>
