import { request, fetchBlob } from './api.js';
const enc = encodeURIComponent;
const write = (path, body = {}, method = 'POST') => request(path, { method, headers: { 'Content-Type':'application/json' }, body:JSON.stringify(body) });
export const checked = (result) => { if (result?.ok === false || result?.error) throw new Error(result.error || '操作失败'); return result; };
export const getCloudStatus = () => request('/v1/cloud/status');
export const cloudLogin = () => write('/v1/cloud/login');
export const cloudLogout = () => write('/v1/cloud/logout');
export const connectorAction = (name, action, body = {}, method = 'POST') => write(`/v1/connectors/${enc(name)}/${action}`, body, method);
export const connectManaged = (name, access) => connectorAction(name, 'connect-managed', access ? { access } : {});
export const connectMcpBacked = (name) => connectorAction(name, 'mcp-connect');
export const accountAction = (name, collection, id, action) => connectorAction(name, `${collection}/${enc(id)}/${action}`);
export const getConnectorStatus = (name) => request(`/v1/connectors/${enc(name)}/status`);
export const allowUser = (name, user_id, team_id, displayName) => connectorAction(name, 'allow', { user_id, ...(team_id ? {team_id} : {}), ...(displayName ? {name:displayName}: {}) });
export const disallowUser = (name, user_id, team_id) => connectorAction(name, 'disallow', { user_id, ...(team_id ? {team_id} : {}) });
export const resolveUnauthorized = (name,id,action) => connectorAction(name, `unauthorized/${enc(id)}`, {action});
export const slackDirectory = (team, q='') => request(`/v1/connectors/slack/workspaces/${enc(team)}/directory?${new URLSearchParams({q})}`);
export const slackChannels = (team, q='') => request(`/v1/connectors/slack/workspaces/${enc(team)}/channels?${new URLSearchParams({q})}`);
export const slackOwner = (user_id, action, name) => connectorAction('slack', `approval-owners/${action}`, {user_id,...(name ? {name}: {})});
export const getSessionConnections = (id,persona) => request(`/v1/sessions/${enc(id)}/connections?${new URLSearchParams({persona:persona || ''})}`);
export const setSessionConnection = (id,connector,enabled,clear=false) => write(`/v1/sessions/${enc(id)}/connections`,{connector,enabled,...(clear?{clear:true}:{})});
export const getMcpTools = name => request(`/v1/mcp/${enc(name)}/tools`);
export const getMcpTrust = name => request(`/v1/mcp/${enc(name)}/trust`);
export const revokeMcpTrust = (name,tool) => request(`/v1/mcp/${enc(name)}/trust/${enc(tool)}`,{method:'DELETE'});
export const convertMcpTrust = name => write(`/v1/mcp/${enc(name)}/trust/convert`);
export const connectMcp = name => write(`/v1/mcp/${enc(name)}/connect`);
export const signoutMcp = name => write(`/v1/mcp/${enc(name)}/signout`);
export const reloadMcp = () => write('/v1/mcp/reload');
export const revealMcpConfig = () => write('/v1/mcp/config/reveal');
export const getInbox = async (session_id='',state='pending') => (await request(`/v1/inbox?${new URLSearchParams({...session_id?{session_id}:{},...state?{state}:{}})}`)).items || [];
export const resolveInboxItem = (id,resolution) => write(`/v1/inbox/${enc(id)}/resolve`,{resolution});
export const getUnattended = async id => !!(await request(`/v1/sessions/${enc(id)}/unattended`)).unattended;
export const setUnattended = (id,unattended) => write(`/v1/sessions/${enc(id)}/unattended`,{unattended});
export const getSubscriptions = async () => (await request('/v1/subscriptions')).subscriptions || [];
export const getRecentChannels = async () => (await request('/v1/channels/recent')).channels || [];
export const subscribeChannel = (session_id,channel) => write('/v1/subscriptions',{session_id,channel});
export const unsubscribeChannel = (session_id,channel) => write('/v1/subscriptions/remove',{session_id,channel});
export const getInboxRouting = async () => (await request('/v1/inbox/routing')).bindings || [];
export const setInboxBinding = (name,channel,target) => write('/v1/inbox/routing/binding',{name,channel,target});
export const getDmRoute = async () => (await request('/v1/messaging/dm-route')).dm_session || '';
export const setDmRoute = session_id => write('/v1/messaging/dm-route',{session_id});
export const getUnrouted = async () => (await request('/v1/unrouted')).items || [];
export const getTeamChat = id => request(`/v1/teams/${enc(id)}/chat`);
export const postTeamChat = (id,text) => write(`/v1/teams/${enc(id)}/chat`,{text});
export const boardAttachment = (id,name) => fetchBlob(`/v1/sessions/${enc(id)}/board/attachment?${new URLSearchParams({name})}`);
